
package com.winning;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorldResponse")
    public String helloWorld();

    /**
     * 
     * @param inXml
     * @param queryInhosWardInfoResult
     * @param outXml
     */
    @WebMethod(operationName = "QueryInhosWardInfo", action = "http://tempuri.org/QueryInhosWardInfo")
    @RequestWrapper(localName = "QueryInhosWardInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryInhosWardInfo")
    @ResponseWrapper(localName = "QueryInhosWardInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryInhosWardInfoResponse")
    public void queryInhosWardInfo(
            @WebParam(name = "InXml", targetNamespace = "http://tempuri.org/")
                    String inXml,
            @WebParam(name = "OutXml", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
                    Holder<String> outXml,
            @WebParam(name = "QueryInhosWardInfoResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
                    Holder<Boolean> queryInhosWardInfoResult);

    /**
     * 
     * @param queryInhosWardInfoItemResult
     * @param inXml
     * @param outXml
     */
    @WebMethod(operationName = "QueryInhosWardInfoItem", action = "http://tempuri.org/QueryInhosWardInfoItem")
    @RequestWrapper(localName = "QueryInhosWardInfoItem", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryInhosWardInfoItem")
    @ResponseWrapper(localName = "QueryInhosWardInfoItemResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryInhosWardInfoItemResponse")
    public void queryInhosWardInfoItem(
            @WebParam(name = "InXml", targetNamespace = "http://tempuri.org/")
                    String inXml,
            @WebParam(name = "OutXml", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
                    Holder<String> outXml,
            @WebParam(name = "QueryInhosWardInfoItemResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
                    Holder<Boolean> queryInhosWardInfoItemResult);

    /**
     * 
     * @param queryDoctResult
     * @param inXml
     * @param outXml
     */
    @WebMethod(operationName = "QueryDoct", action = "http://tempuri.org/QueryDoct")
    @RequestWrapper(localName = "QueryDoct", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryDoct")
    @ResponseWrapper(localName = "QueryDoctResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryDoctResponse")
    public void queryDoct(
            @WebParam(name = "InXml", targetNamespace = "http://tempuri.org/")
                    String inXml,
            @WebParam(name = "OutXml", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
                    Holder<String> outXml,
            @WebParam(name = "QueryDoctResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
                    Holder<Boolean> queryDoctResult);

    /**
     * 
     * @param queryAllDeptResult
     * @param inXml
     * @param outXml
     */
    @WebMethod(operationName = "QueryAllDept", action = "http://tempuri.org/QueryAllDept")
    @RequestWrapper(localName = "QueryAllDept", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryAllDept")
    @ResponseWrapper(localName = "QueryAllDeptResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryAllDeptResponse")
    public void queryAllDept(
            @WebParam(name = "InXml", targetNamespace = "http://tempuri.org/")
                    String inXml,
            @WebParam(name = "OutXml", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
                    Holder<String> outXml,
            @WebParam(name = "QueryAllDeptResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
                    Holder<Boolean> queryAllDeptResult);

    /**
     * 
     * @param inXml
     * @param outXml
     * @param queryJhRegRecordResult
     */
    @WebMethod(operationName = "QueryJhRegRecord", action = "http://tempuri.org/QueryJhRegRecord")
    @RequestWrapper(localName = "QueryJhRegRecord", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryJhRegRecord")
    @ResponseWrapper(localName = "QueryJhRegRecordResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryJhRegRecordResponse")
    public void queryJhRegRecord(
            @WebParam(name = "InXml", targetNamespace = "http://tempuri.org/")
                    String inXml,
            @WebParam(name = "OutXml", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
                    Holder<String> outXml,
            @WebParam(name = "QueryJhRegRecordResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
                    Holder<Boolean> queryJhRegRecordResult);

}
